from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'webapp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^siteadmin/', include(admin.site.urls)),
    url(r'', include('registration.backends.default.urls')),
    url(r'', include('django.contrib.auth.urls')),
    url(r'^$', 'grumblr.views.home', name='home'),
    url(r'^changepassword$', 'django.contrib.auth.views.password_change', name='change_password'),
    url(r'^changepassworddone$', 'django.contrib.auth.views.password_change_done'),
    url(r'^login$', 'django.contrib.auth.views.login', {'template_name':'grumblr/login.html'}, name='login'),
    url(r'^reset/done/grumblr/login$', 'django.contrib.auth.views.login', {'template_name':'grumblr/login.html'}, name='login'),
    url(r'^logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^grumblr/login$', 'django.contrib.auth.views.login', {'template_name':'grumblr/login.html'}, name='login'),
    url(r'^search-result$', 'grumblr.views.search', name='search'),
    url(r'^register$', 'grumblr.views.register', name='register'),
    url(r'^add-post', 'grumblr.views.add_post', name='addPost'),
    url(r'^delete-post/(?P<id>\d+)$', 'grumblr.views.delete_post', name='deletePost'),
    url(r'^follower$', 'grumblr.views.followerStream', name='follower'),
    url(r'^profile$', 'grumblr.views.getProfile', name='profile'),
    url(r'^follower-profile/(?P<id>\d+)$', 'grumblr.views.get_follower_profile', name='followerProfile'),
    url(r'^edit-profile/(?P<id>\d+)$', 'grumblr.views.edit_profile', name='editProfile'),
    url(r'^add-profile$', 'grumblr.views.add_profile', name='addProfile'),
    url(r'^photo/(?P<id>\d+)&(?P<user_id>\d+)$', 'grumblr.views.get_photo', name='photo'),
    url(r'^post-photo/(?P<post_id>\d+)$', 'grumblr.views.get_post_photo', name='post_photo'),
    url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', 'grumblr.views.confirm_registration', name='confirm'),
    url(r'^add-comment/(?P<post_id>\d+)&(?P<user_id>\d+)$', 'grumblr.views.add_comment', name='addComment'),
    url(r'^dislike/(?P<post_id>\d+)&(?P<user_id>\d+)$', 'grumblr.views.dislike', name='dislike'),
    url(r'^add-follower/(?P<id>\d+)$', 'grumblr.views.add_follower', name='addFollower'),
    url(r'^block-follower/(?P<id>\d+)$', 'grumblr.views.block_follower', name='blockFollower'),
    url(r'^resetpassword/passwordsent/$', 'django.contrib.auth.views.password_reset_done', name='password_reset_done'),
    url(r'^resetpassword$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm', name='password_reset_confirm'),
    url(r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete', name='password_reset_complete'),
    url(r'^get-grumbles$', 'grumblr.views.get_grumbles'),
                       
)
